const db = require('../db');
const notifications = require('../notifications');

const SCHEMA = '"FO_CARE_APP"';

/**
 * Ported from n8n's fo_care_tickets webhook, action "create_ticket".
 * Structurally mirrors hotline.js's createHotlineTicket: ticket insert +
 * optional attachment insert in one transaction.
 *
 * No RBAC gate — unlike admin/manager/resolver/hotline actions, there is
 * no Postgres table of Field Officers to check against yet (tracked
 * separately as a future "FO Care users" table, synced from Snowflake).
 * fo_email / fo_name / site_id / site_name are trusted as already
 * re-derived server-side by the caller (GAS, from the FO's authenticated
 * Google session + the FSPM sheet) before this action is ever invoked —
 * same trust boundary n8n has today, just moved.
 *
 * custom_fields is stored as a real jsonb object ($9::jsonb) rather than
 * n8n's json-string-in-jsonb quirk (to_jsonb($9::text)). Confirmed safe:
 * tickets.js's getTicketDetail already branches on
 * `typeof custom_fields === 'string'` specifically to unwrap that old
 * quirk, so existing rows keep working through that branch unchanged —
 * new rows written here just never hit it.
 *
 * ticket_number is NOT set here — the live schema assigns it via a
 * BEFORE INSERT trigger (trg_tickets_assign_number ->
 * assign_ticket_number()), confirmed from the schema export, not
 * generated by application code.
 *
 * Resolver-notification email (previously an inline Gmail node in n8n,
 * right after the same INSERT) is now a call to the dedicated
 * notifications webhook — see notifications.js — so a slow or failed
 * email can never block or fail the FO's "ticket submitted" response.
 */
async function createFoTicket(payload) {
  const client = await db.pool.connect();
  try {
    await client.query('BEGIN');

    const { rows } = await client.query(
      `INSERT INTO ${SCHEMA}.tickets (
        category_id, fo_email, fo_name, site_id, site_name,
        farmer_account, farmer_name, description, custom_fields, sla_due_at,
        source_system
      )
      SELECT
        $1, $2, $3, $4, $5,
        NULLIF(TRIM($6), ''), NULLIF(TRIM($7), ''), NULLIF(TRIM($8), ''),
        $9::jsonb,
        now() + (c.sla_hours || ' hours')::interval,
        'fo_app'
      FROM ${SCHEMA}.ticket_categories c WHERE c.id = $1
      RETURNING id, ticket_number, status_code, created_at`,
      [
        payload.category_id,
        payload.fo_email,
        payload.fo_name,
        payload.site_id,
        payload.site_name,
        payload.farmer_account || '',
        payload.farmer_name || '',
        payload.description || '',
        payload.custom_fields || {},
      ]
    );

    if (rows.length === 0) {
      await client.query('ROLLBACK');
      return { success: false, error: 'Failed to create ticket. Check that the category exists.' };
    }

    const ticket = rows[0];

    if (payload.attachment_url) {
      await client.query(
        `INSERT INTO ${SCHEMA}.ticket_attachments (ticket_id, file_url, file_name, uploaded_by_role)
         VALUES ($1, $2, $3, 'fo')`,
        [ticket.id, payload.attachment_url, payload.attachment_file_name || null]
      );
    }

    await client.query('COMMIT');

    await notifications.notifyNewTicket(ticket.id);

    return {
      success: true,
      data: {
        id: Number(ticket.id),
        ticket_number: ticket.ticket_number,
        status_code: ticket.status_code,
        created_at: ticket.created_at,
      },
    };
  } catch (err) {
    await client.query('ROLLBACK');
    throw err;
  } finally {
    client.release();
  }
}

module.exports = { createFoTicket };