const db = require('../db');
const notifications = require('../notifications');

const SCHEMA = '"FO_CARE_APP"';

/**
 * Ported from n8n's fo_care_tickets webhook, action "create_ticket".
 * Structurally mirrors hotline.js's createHotlineTicket: ticket insert +
 * optional attachment insert in one transaction.
 *
 * No RBAC gate — unlike admin/manager/resolver/hotline actions, there is
 * no Postgres table of Field Officers to check against yet (tracked
 * separately as a future "FO Care users" table, synced from Snowflake).
 * fo_email / fo_name / site_id / site_name are trusted as already
 * re-derived server-side by the caller (GAS, from the FO's authenticated
 * Google session + the FSPM sheet) before this action is ever invoked —
 * same trust boundary n8n has today, just moved.
 *
 * custom_fields is stored as a real jsonb object ($9::jsonb) rather than
 * n8n's json-string-in-jsonb quirk (to_jsonb($9::text)). Confirmed safe:
 * tickets.js's getTicketDetail already branches on
 * `typeof custom_fields === 'string'` specifically to unwrap that old
 * quirk, so existing rows keep working through that branch unchanged —
 * new rows written here just never hit it.
 *
 * ticket_number is NOT set here — the live schema assigns it via a
 * BEFORE INSERT trigger (trg_tickets_assign_number ->
 * assign_ticket_number()), confirmed from the schema export, not
 * generated by application code.
 *
 * Resolver-notification email (previously an inline Gmail node in n8n,
 * right after the same INSERT) is now a call to the dedicated
 * notifications webhook — see notifications.js — so a slow or failed
 * email can never block or fail the FO's "ticket submitted" response.
 */
async function createFoTicket(payload) {
  const client = await db.pool.connect();
  let ticket;

  try {
    await client.query('BEGIN');

    const { rows } = await client.query(
      `INSERT INTO ${SCHEMA}.tickets (
        category_id, fo_email, fo_name, site_id, site_name,
        farmer_account, farmer_name, description, custom_fields, sla_due_at,
        source_system
      )
      SELECT
        $1, $2, $3, $4, $5,
        NULLIF(TRIM($6), ''), NULLIF(TRIM($7), ''), NULLIF(TRIM($8), ''),
        $9::jsonb,
        now() + (c.sla_hours || ' hours')::interval,
        'core_program'
      FROM ${SCHEMA}.ticket_categories c WHERE c.id = $1
      RETURNING id, ticket_number, status_code, created_at`,
      [
        payload.category_id,
        payload.fo_email,
        payload.fo_name,
        payload.site_id,
        payload.site_name,
        payload.farmer_account || '',
        payload.farmer_name || '',
        payload.description || '',
        payload.custom_fields || {},
      ]
    );

    if (rows.length === 0) {
      await client.query('ROLLBACK');
      return { success: false, error: 'Failed to create ticket. Check that the category exists.' };
    }

    ticket = rows[0];

    if (payload.attachment_url) {
      await client.query(
        `INSERT INTO ${SCHEMA}.ticket_attachments (ticket_id, file_url, file_name, uploaded_by_role)
         VALUES ($1, $2, $3, 'fo')`,
        [ticket.id, payload.attachment_url, payload.attachment_file_name || null]
      );
    }

    await client.query('COMMIT');
  } catch (err) {
    // Only DB statements above this point can land here — the ticket is
    // NOT yet committed if we reach this catch, so a real ROLLBACK is
    // always the correct thing to do.
    await client.query('ROLLBACK');
    throw err;
  } finally {
    client.release();
  }

  // Deliberately OUTSIDE the transaction's try/catch/finally above: the
  // ticket is already safely committed by this point, so nothing that
  // happens here — a slow webhook, a thrown error, anything — can ever
  // roll back or fail a ticket that already exists. (notifyNewTicket
  // also swallows its own errors internally, so this is a second,
  // independent layer of protection against the exact same class of bug.)
  await notifications.notifyNewTicket(ticket.id);

  return {
    success: true,
    data: {
      id: Number(ticket.id),
      ticket_number: ticket.ticket_number,
      status_code: ticket.status_code,
      created_at: ticket.created_at,
    },
  };
}

/**
 * Ported from n8n's fo_care_tickets webhook, action "get_my_tickets".
 * Scope is fo_email + site_id together (not fo_email alone) — matches
 * n8n's Edit Fields -> Get_FO_Tickets exactly. Both values are trusted as
 * already re-derived server-side by the caller from the FO's authenticated
 * session, same as createFoTicket above.
 */
async function getMyTickets(payload) {
  const { rows } = await db.query(
    `SELECT
      t.id, t.ticket_number, c.label AS category_label, t.status_code,
      s.label AS status_label, t.description, t.farmer_account, t.farmer_name,
      t.sla_due_at, t.created_at, t.updated_at,
      (t.sla_due_at IS NOT NULL AND now() > t.sla_due_at AND t.status_code IN ('OPEN', 'IN_PROGRESS', 'REOPENED')) AS is_overdue
    FROM ${SCHEMA}.tickets t
    JOIN ${SCHEMA}.ticket_categories c ON c.id = t.category_id
    JOIN ${SCHEMA}.ticket_statuses s ON s.code = t.status_code
    WHERE t.fo_email = $1 AND t.site_id = $2
    ORDER BY t.created_at DESC`,
    [payload.fo_email, payload.site_id]
  );

  return {
    success: true,
    data: rows.map((row) => ({
      id: row.id != null ? Number(row.id) : null,
      ticket_number: row.ticket_number ?? null,
      category_label: row.category_label ?? null,
      status_code: row.status_code ?? null,
      status_label: row.status_label ?? null,
      description: row.description ?? null,
      farmer_account: row.farmer_account ?? null,
      farmer_name: row.farmer_name ?? null,
      sla_due_at: row.sla_due_at ?? null,
      created_at: row.created_at ?? null,
      updated_at: row.updated_at ?? null,
      is_overdue: Boolean(row.is_overdue),
    })),
  };
}

/**
 * Ported from n8n's fo_care_tickets webhook, action "get_ticket_comments".
 * Ownership check is embedded in the JOIN (t.fo_email = $2), matching n8n
 * exactly — an FO requesting a ticket_id that isn't theirs just gets an
 * empty array back, never another FO's comments and never a distinct
 * "not yours" error. Same pattern as tickets.js's addComment.
 */
async function getTicketComments(payload) {
  const { rows } = await db.query(
    `SELECT tc.author_role, tc.author_name, tc.comment_text, tc.created_at
     FROM ${SCHEMA}.ticket_comments tc
     JOIN ${SCHEMA}.tickets t ON t.id = tc.ticket_id
     WHERE tc.ticket_id = $1 AND t.fo_email = $2
     ORDER BY tc.created_at ASC`,
    [payload.ticket_id, payload.fo_email]
  );

  return {
    success: true,
    data: rows.map((row) => ({
      author_role: row.author_role ?? null,
      author_name: row.author_name ?? null,
      comment_text: row.comment_text ?? null,
      created_at: row.created_at ?? null,
    })),
  };
}

/**
 * Ported from n8n's fo_care_tickets webhook, action "lookup_account".
 * Advisory only — GAS's lookupAccountNumber() already treats "not found"
 * as a soft failure that never blocks ticket submission, so this just
 * needs to return an honest empty/found result, same as n8n.
 *
 * FIXED during porting: n8n's version built this query by interpolating
 * account_number directly into the SQL text via an expression
 * (`={{ $json.body.payload.account_number }}`) rather than a parameterized
 * query — a real SQL-injection hole, since the value comes straight from
 * the FO app with no server-side validation. Parameterized here ($1),
 * consistent with every other query in this codebase.
 */
async function lookupAccount(payload) {
  const { rows } = await db.query(
    `SELECT account_number, client_name, district, site_name, site_id, fo_email, group_name
     FROM ${SCHEMA}.account_directory
     WHERE account_number::text = $1::text
     LIMIT 1`,
    [payload.account_number]
  );

  return { success: true, data: rows };
}

module.exports = { createFoTicket, getMyTickets, getTicketComments, lookupAccount };